[settings]
strict = true
verbose = true
doctype = "<!DOCTYPE html>"
clean_urls = false
page_file_extensions = ["htm", "html", "md"]
ignore_extensions = ["draft"]
plugin_discovery = true
plugin_dirs = ["PandocRulebookBase/soupault/plugins"]
pretty_print_html = false

site_dir = "build/sources/soupault/site"
build_dir = "build/run/web"

default_template_file = "PandocRulebookBase/soupault/template/main.html"
default_content_selector = "article"
default_content_action = "append_child"

[preprocessors]
md = 'PandocRulebookBase/scripts/sh/tool_pandoc-html.sh'

[custom_options]

##
## Base Templates
##

[templates.redirect]
file = "PandocRulebookBase/soupault/template/redirect.html"
content_selector = 'head'
content_action = "append_child"
section = ""

[templates.nonav]
file = "PandocRulebookBase/soupault/template/main_nonav.html"
section = "apps/"
include_subsections = true

##
## Widgets: Base Formatting
##

[widgets.base-format_header]
widget = "include"
selector = "header"
file = "template/web/components/layout_header.html"

[widgets.base-format_meta]
widget = "include"
selector = "head"
file = "template/web/components/head.html"

[widgets.base-format_menu-template]
widget = "include"
selector = ["#menu-inner"]
file = "PandocRulebookBase/soupault/template/menu.html"

[widgets.base-format_menu-footer]
widget = "exec"
selector = ["#menu-footer"]
command = "PandocRulebookBase/scripts/sh/tool_pandoc-html.sh template/web/components/menu_footer.md"

[widgets.base-format_menu-index]
after = "base-format_menu-template"
widget = "exec"
selector = ["#gen-menu"]
command = "PandocRulebookBase/scripts/sh/tool_pandoc-html.sh template/web/components/menu_index.md"

[widgets.page-title]
widget = "title"
selector = "h1:not(.internal)"
default = "Project Name"
append = " | Project Name"
force = true
keep = true

[widgets.generator-meta]
widget = 'insert_html'
selector = 'head'
html = '<meta name="generator" content="crabsoup">'

##
## Widgets: Markup Processing
##

[widgets.base_fix-styles]
widget = "base_fix-styles"

[widgets.base_cleanup]
after = ["base_process-toc", "rulebook_alt-span", "base_opengraph"]
widget = "base_cleanup"

[widgets.base_opengraph]
after = ["table-of-contents", "page-title"]
widget = "base_opengraph"

[widgets.highlight]
widget = "preprocess_element"
selector = '*[class^="language-"]'
command = 'highlight --force -O html -f --syntax=$(echo $ATTR_CLASS | sed -e "s/language-//")'

[widgets.wrap-boxes]
after = ["rulebook_formats"]
widget = "wrap"
wrapper = """ <div> """
selector = [".box > table", ".box > ul", ".box > ol", ".box > hr", ".box > section"]

[widgets.base_hcard]
after = ["base-format_menu-index", "base-format_menu-footer"]
widget = "base_hcard"

[widgets.images]
after = ["base-format_menu-index", "base-format_menu-footer", "base_hcard", "base_opengraph"]
widget = "base_images"

##
## Widgets: Rulebook Formatting
##

[widgets.ver-tag]
widget = "exec"
selector = ["#ver-tag"]
command = 'git describe --always --dirty=-DIRTY | tr -d "\n"'
action = "replace_content"

[widgets.rev-tag]
widget = "exec"
selector = ["#rev-tag"]
command = 'git rev-parse HEAD | tr -d "\n"'
action = "replace_content"

[widgets.rulebook_alt-span]
widget = "rulebook_alt-span"

[widgets.rulebook_formats]
after = "table-of-contents"
widget = "rulebook_formats"

##
## Widgets: Table of Contents
##

[widgets.table-of-contents]
after = "base-format_menu-index"
widget = "toc"
selector = "#gen-toc"

min_level = 2
toc_list_class = "toc"
numbered_list = false
heading_links = true
heading_link_text = "ยง"
heading_link_class = "section"
heading_links_append = true

[widgets.base_process-toc]
after = "table-of-contents"
widget = "base_process-toc"

[widgets.website_no-toc-format]
after = "base_process-toc"
widget = "website_no-toc-format"